### ISSUE TITLE
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1762 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by mwawrusch** [BendixMa/sliding-sheet#1]
Great widget, thanks for posting. I ran into a problem, using this code:
```
void  showSlider(BuildContext context, String newIssuerId) async {
  final result = await showSlidingBottomSheet(
    context,
    elevation: 8,
    cornerRadius: 16,
    snapSpec: const SnapSpec(
      snap: true,
      snappings: [0.7, 1.0],
      positioning: SnapPositioning.relativeToAvailableSpace,
    ),
    builder: (context, state) {
      return Container(
        height: MediaQuery.of(context).size.height,
        child: Center(
          child: Material(
            child: InkWell(
              onTap: () => Navigator.pop(context, 'This is the result.'),
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Text(
                  'This is the content of the sheet',
                  style: Theme.of(context).textTheme.body1,
                ),
              ),
            ),
          ),
        ),
      );
    },
  );

  print(result); // This is the result.
}
```

After the second invocation (e.g. open/close) I get the following error:

```

════════ Exception caught by gesture ═══════════════════════════════════════════
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1762 pos 12: '!_debugLocked': is not true.
════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1762 pos 12: '!_debugLocked': is not true.
#0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:36:5)
#2      NavigatorState.push 
package:flutter/…/widgets/navigator.dart:1762
#3      Navigator.push 
package:flutter/…/widgets/navigator.dart:1107
#4      showSlidingBottomSheet 
package:sliding_sheet/src/sheet.dart:1088
#5      showSlider 
package:roji_wallet/…/asset_detail_overlay/screen_asset_detail_overlay2.dart:5
<asynchronous suspension>
#6      PortfolioRow.build.<anonymous closure> 
package:roji_wallet/…/portfolio/portfolio_row.dart:23
#7      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:654
#8      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:729
#9      GestureRecogn<…>
```

which is caused by 
```
return Navigator.push(
    context,
    _TransparentRoute(
      duration: duration,
      builder: (context, animation, route) => SlidingSheet(
        route: route,
        snapSpec: snapSpec,
        duration: duration,
        color: color ??
            theme.bottomSheetTheme.backgroundColor ??
            theme.dialogTheme.backgroundColor ??
            theme.dialogBackgroundColor ??
            theme.backgroundColor,
        backdropColor: backdropColor,
        shadowColor: shadowColor,
        elevation: elevation,
        padding: padding,
        margin: margin,
        border: border,
        cornerRadius: cornerRadius,
        closeOnBackdropTap: dismissableBackground,
        builder: builder,
        headerBuilder: headerBuilder,
        footerBuilder: footerBuilder,
        listener: listener,
        controller: controller,
        scrollSpec: scrollSpec,
        maxWidth: maxWidth,
      ),
    ),
``` 
starting at line 1088 in sheet.dart

**Comment by mwawrusch** [comment]
After changing the above code and invoking it correctly using async function I get this instead:
```

RangeError (index): Invalid value: Valid value range is empty: -1

When the exception was thrown, this was the stack
#0      List.[]  (dart:core-patch/growable_array.dart:147:60)
#1      List.removeLast  (dart:core-patch/growable_array.dart:213:20)
#2      _navigatePop 
package:roji_wallet/…/reducers/navigation_reducers.dart:24
#3      TypedReducer.call 
package:redux/src/utils.dart:103
#4      combineReducers.<anonymous closure> 
package:redux/src/utils.dart:248
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#6b151
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(225.7, 232.0)
    sent tap down
```

**Comment by mwawrusch** [comment]
So I figured it out, I did not call the method asynchronously (and did not define the signature correctly, which should be Future<void>, not void.

Thanks
